# Generated by Django 4.0.6 on 2022-08-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name="Task's status"),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=1000, verbose_name="Task's name"),
        ),
    ]
