# Generated by Django 4.0.6 on 2022-08-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_tasks', '0003_alter_task_status_alter_task_task_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
