# Generated by Django 4.0.6 on 2022-08-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_tasks', '0006_task_created_alter_task_id_project_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_deletable',
        ),
    ]
