# Generated by Django 4.0.6 on 2022-08-22 09:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_email'),
        ('_tasks', '0007_remove_project_is_deletable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status']},
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('task_name', models.CharField(max_length=1000, verbose_name='Subtask name')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Subtask status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_tasks.task')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
